const sectors=[['Baixa Tensão','#e7b321'],['TC','#21965a'],['TP','#177fc3'],['Resina','#985bd0'],['Montagem','#ed8027'],['Testes','#65767e']];
const home=document.querySelector('#home'),detail=document.querySelector('#detail'),content=document.querySelector('#content'),heading=document.querySelector('#section-title');
let current='home';
function openScreen(screen,push=true){current=screen;home.hidden=screen!=='home';detail.hidden=screen==='home';if(push)location.hash=screen==='home'?'':screen;
if(screen==='home')return;
const titles={sectors:'Setores',search:'Buscar instrução',qr:'Acesso por código da IT',products:'Produtos',mine:'Minhas ITs',settings:'Configurações'};heading.textContent=titles[screen]||screen;content.replaceChildren();
if(screen==='sectors'){const input=document.createElement('input');input.placeholder='Buscar setor…';input.setAttribute('aria-label','Buscar setor');const list=document.createElement('div');list.className='sector-list';content.append(input,list);const render=()=>{list.replaceChildren();sectors.filter(([name])=>name.toLocaleLowerCase('pt-BR').includes(input.value.toLocaleLowerCase('pt-BR'))).forEach(([name,color])=>{const button=document.createElement('button');button.className='sector';button.style.setProperty('--color',color);const badge=document.createElement('span');badge.className='badge';badge.textContent='▤';const label=document.createElement('strong');label.textContent=name;const arrow=document.createElement('span');arrow.className='arrow';arrow.textContent='›';button.append(badge,label,arrow);button.onclick=()=>openScreen('setor/'+name);list.append(button)});if(!list.children.length)list.textContent='Nenhum setor encontrado.'};input.oninput=render;render();}
else if(screen.startsWith('setor/')){heading.textContent=screen.slice(6);empty('Nenhuma instrução cadastrada neste setor.');}
else if(screen==='search'){const input=document.createElement('input');input.placeholder='Digite o nome ou código da instrução';input.setAttribute('aria-label','Buscar instrução');content.append(input);empty('O catálogo de instruções ainda não foi cadastrado.');}
else if(screen==='qr'){empty('A leitura pela câmera estará disponível após cadastrar as instruções e seus QR Codes.');}
else if(screen==='settings'){const button=document.createElement('button');button.className='action';const sync=()=>button.textContent=document.body.classList.contains('large')?'Usar texto padrão':'Usar texto ampliado';sync();button.onclick=()=>{document.body.classList.toggle('large');localStorage.setItem('it-digital-large',document.body.classList.contains('large'));sync()};content.append(button);}
else{empty(screen==='products'?'Nenhum produto cadastrado.':'Nenhuma instrução favorita adicionada.');}}
function empty(text){const p=document.createElement('p');p.className='empty';p.textContent=text;content.append(p)}
document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>openScreen(b.dataset.screen));document.querySelector('#back').onclick=()=>openScreen(current.startsWith('setor/')?'sectors':'home');window.addEventListener('hashchange',()=>openScreen(decodeURIComponent(location.hash.slice(1))||'home',false));
if(localStorage.getItem('it-digital-large')==='true')document.body.classList.add('large');
function tick(){document.querySelector('#clock').textContent=new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}tick();setInterval(tick,1000);openScreen(decodeURIComponent(location.hash.slice(1))||'home',false);
